#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Sep 14, 2021 05:07:12 PM JST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True


global auto_send_checked, auto_clear_checked, send_encoding, receive_encoding, send_one_line_checked, buffer_size, \
    port_num


def set_Tk_var():
    global auto_send_checked
    auto_send_checked = tk.IntVar()
    global auto_clear_checked
    auto_clear_checked = tk.IntVar()
    global send_encoding
    send_encoding = tk.StringVar()
    global receive_encoding
    receive_encoding = tk.StringVar()
    global send_one_line_checked
    send_one_line_checked = tk.IntVar()
    global buffer_size
    buffer_size = tk.IntVar()
    global port_num
    port_num = tk.IntVar()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def show_ui():
    from gui import ui
    ui.vp_start_gui()


def setup_ui():
    from gui import ui
    ui.vp_setup_gui()
