#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Sep 14, 2021 05:06:34 PM JST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m46" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black
    wm focusmodel $top passive
    wm geometry $top 487x488+726+296
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 5524 1131
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Form1"
    vTcl:DefineAlias "$top" "MainForm" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m46 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0
    text $top.tex48 \
        -background white -font TkTextFont -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -undo 1 -width 390
    $top.tex48 configure -font "TkTextFont"
    $top.tex48 insert end text
    vTcl:DefineAlias "$top.tex48" "IP" vTcl:WidgetProc "MainForm" 1
    bind $top.tex48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Server Address}
    }
    checkbutton $top.che51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Auto send messages when connected to server} \
        -variable auto_send_checked
    vTcl:DefineAlias "$top.che51" "Auto_Send" vTcl:WidgetProc "MainForm" 1
    checkbutton $top.che56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Auto clear log next connection } \
        -variable auto_clear_checked
    vTcl:DefineAlias "$top.che56" "Auto_Clear_Log" vTcl:WidgetProc "MainForm" 1
    ttk::progressbar $top.tPr58 \
        -length 481
    vTcl:DefineAlias "$top.tPr58" "Progress" vTcl:WidgetProc "MainForm" 1
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #d8d8d8 -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Status: Disconnected | ↑ 0 b/s | ↓ 0 b/s}
    vTcl:DefineAlias "$top.lab59" "Status" vTcl:WidgetProc "MainForm" 1
    ttk::combobox $top.tCo60 \
        -values {<Put the same encoding items>} -exportselection 0 \
        -textvariable send_encoding -foreground {} -background {} \
        -takefocus {} -cursor hand2
    vTcl:DefineAlias "$top.tCo60" "Send_Encoding" vTcl:WidgetProc "MainForm" 1
    ttk::combobox $top.tCo61 \
        -values {<Put the same encoding items>} -exportselection 0 \
        -textvariable receive_encoding -foreground {} -background {} \
        -takefocus {} -cursor hand2
    vTcl:DefineAlias "$top.tCo61" "Receive_Encoding" vTcl:WidgetProc "MainForm" 1
    checkbutton $top.che63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Send one line at a time} \
        -variable send_one_line_checked
    vTcl:DefineAlias "$top.che63" "Send_One" vTcl:WidgetProc "MainForm" 1
    ttk::separator $top.tSe64
    vTcl:DefineAlias "$top.tSe64" "S1" vTcl:WidgetProc "MainForm" 1
    button $top.but65 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -state disabled -text Send
    vTcl:DefineAlias "$top.but65" "Send" vTcl:WidgetProc "MainForm" 1
    button $top.but66 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Connect
    vTcl:DefineAlias "$top.but66" "Action" vTcl:WidgetProc "MainForm" 1
    button $top.but67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Clear Input}
    vTcl:DefineAlias "$top.but67" "Clear_In" vTcl:WidgetProc "MainForm" 1
    button $top.but68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -cursor hand2 \
        -disabledforeground #a3a3a3 -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Clear Logs}
    vTcl:DefineAlias "$top.but68" "Clear_Logs" vTcl:WidgetProc "MainForm" 1
    spinbox $top.spi69 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground black \
        -from -1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable buffer_size -to 2147483647.0
    vTcl:DefineAlias "$top.spi69" "Buffer" vTcl:WidgetProc "MainForm" 1
    spinbox $top.spi73 \
        -activebackground #f9f9f9 -background white -buttonbackground #d9d9d9 \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground black \
        -from 1.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground blue \
        -selectforeground white -textvariable port_num -to 65535.0
    vTcl:DefineAlias "$top.spi73" "Port" vTcl:WidgetProc "MainForm" 1
    ttk::separator $top.tSe74
    vTcl:DefineAlias "$top.tSe74" "S2" vTcl:WidgetProc "MainForm" 1
    label $top.lab77 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Input
    vTcl:DefineAlias "$top.lab77" "Input_Guide" vTcl:WidgetProc "MainForm" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr79 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125
    vTcl:DefineAlias "$top.scr79" "Input" vTcl:WidgetProc "MainForm" 1

    $top.scr79.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground blue \
        -selectforeground white \
        -width 10 \
        -wrap none
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr80 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125
    vTcl:DefineAlias "$top.scr80" "Packet_log" vTcl:WidgetProc "MainForm" 1

    $top.scr80.01 configure -background white \
        -cursor xterm \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground blue \
        -selectforeground white \
        -width 10
    label $top.lab82 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Packet Log}
    vTcl:DefineAlias "$top.lab82" "Log_Guide" vTcl:WidgetProc "MainForm" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tex48 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.02 -width 0 -relwidth 0.801 \
        -height 0 -relheight 0.045 -anchor nw -bordermode ignore
    place $top.che51 \
        -in $top -x 0 -relx 0.012 -y 0 -rely 0.082 -width 0 -relwidth 0.565 \
        -height 0 -relheight 0.041 -anchor nw -bordermode ignore
    place $top.che56 \
        -in $top -x 0 -relx 0.008 -y 0 -rely 0.123 -width 0 -relwidth 0.4 \
        -height 0 -relheight 0.041 -anchor nw -bordermode ignore
    place $top.tPr58 \
        -in $top -x 0 -y 0 -rely 0.963 -width 0 -relwidth 1 -height 0 \
        -relheight 0.049 -anchor nw -bordermode ignore
    place $top.lab59 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.922 -width 0 -relwidth 1.027 \
        -height 0 -relheight 0.029 -anchor nw -bordermode ignore
    place $top.tCo60 \
        -in $top -x 0 -relx 0.626 -y 0 -rely 0.082 -width 0 -relwidth 0.359 \
        -height 0 -relheight 0.049 -anchor nw -bordermode ignore
    place $top.tCo61 \
        -in $top -x 0 -relx 0.626 -y 0 -rely 0.143 -width 0 -relwidth 0.359 \
        -height 0 -relheight 0.049 -anchor nw -bordermode ignore
    place $top.che63 \
        -in $top -x 0 -relx 0.014 -y 0 -rely 0.164 -width 0 -relwidth 0.298 \
        -height 0 -relheight 0.041 -anchor nw -bordermode ignore
    place $top.tSe64 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.221 -width 0 -relwidth 0.965 \
        -height 0 -relheight 0.004 -anchor nw -bordermode ignore
    place $top.but65 \
        -in $top -x 0 -relx 0.226 -y 0 -rely 0.246 -width 92 -relwidth 0 \
        -height 22 -relheight 0 -anchor nw -bordermode ignore
    place $top.but66 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.246 -width 92 -relwidth 0 \
        -height 22 -relheight 0 -anchor nw -bordermode ignore
    place $top.but67 \
        -in $top -x 0 -relx 0.431 -y 0 -rely 0.246 -width 92 -relwidth 0 \
        -height 22 -relheight 0 -anchor nw -bordermode ignore
    place $top.but68 \
        -in $top -x 0 -relx 0.637 -y 0 -rely 0.246 -width 92 -relwidth 0 \
        -height 22 -relheight 0 -anchor nw -bordermode ignore
    place $top.spi69 \
        -in $top -x 0 -relx 0.842 -y 0 -rely 0.246 -width 0 -relwidth 0.144 \
        -height 0 -relheight 0.045 -anchor nw -bordermode ignore
    place $top.spi73 \
        -in $top -x 0 -relx 0.842 -y 0 -rely 0.02 -width 0 -relwidth 0.146 \
        -height 0 -relheight 0.045 -anchor nw -bordermode ignore
    place $top.tSe74 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.311 -width 0 -relwidth 0.965 \
        -height 0 -relheight 0.004 -anchor nw -bordermode ignore
    place $top.lab77 \
        -in $top -x 0 -relx 0.018 -y 0 -rely 0.328 -width 0 -relwidth 0.09 \
        -height 0 -relheight 0.023 -anchor nw -bordermode ignore
    place $top.scr79 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.348 -width 0 -relwidth 0.965 \
        -height 0 -relheight 0.158 -anchor nw -bordermode ignore
    place $top.scr80 \
        -in $top -x 0 -relx 0.021 -y 0 -rely 0.553 -width 0 -relwidth 0.965 \
        -height 0 -relheight 0.35 -anchor nw -bordermode ignore
    place $top.lab82 \
        -in $top -x 0 -relx 0.016 -y 0 -rely 0.512 -width 0 -relwidth 0.214 \
        -height 0 -relheight 0.043 -anchor nw -bordermode ignore
    } ;# end vTcl:withBusyCursor

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

